# docker-compose.yml
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:13000/api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "13000:13000"
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal  # This allows connection to host machine's MySQL
      - DB_USER=root
      - DB_PASSWORD=Yaosong1216!
      - DB_NAME=clockingapp
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This is important for Mac/Linux

networks:
  app-network:
    driver: bridge