name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Source profile and bashrc
            source ~/.profile
            source ~/.bashrc
            
            # Navigate to project
            cd ~/clockingApp
            
            # Ensure correct permissions
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/id_ed25519
            chmod 644 ~/.ssh/id_ed25519.pub
            
            # Pull latest changes
            git pull origin main
            
            # Client build
            cd client 
            npm install
            npm run build
            
            # Server setup
            cd ../server 
            npm install
            
            # Return to root and restart
            cd ..
            pm2 restart ecosystem.config.js