name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Export NVM and PATH
            export NVM_DIR="/home/mmc/.nvm"
            export PATH="/home/mmc/.nvm/versions/node/v20.18.2/bin:$PATH"
            
            # Navigate to project
            cd ~/clockingApp
            
            # Debug: Print versions
            echo "Node version: $(/home/mmc/.nvm/versions/node/v20.18.2/bin/node --version)"
            echo "NPM version: $(/home/mmc/.nvm/versions/node/v20.18.2/bin/npm --version)"
            
            # Pull latest changes
            git pull origin main
            
            # Client build
            echo "Building client..."
            cd client 
            /home/mmc/.nvm/versions/node/v20.18.2/bin/npm install
            /home/mmc/.nvm/versions/node/v20.18.2/bin/npm run build
            
            # Server setup
            echo "Setting up server..."
            cd ../server 
            /home/mmc/.nvm/versions/node/v20.18.2/bin/npm install
            
            # Return to root
            cd ..
            
            # Ensure PM2 is installed globally
            /home/mmc/.nvm/versions/node/v20.18.2/bin/npm install -g pm2
            
            # Restart PM2
            pm2 restart ecosystem.config.js