name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/clockingApp
            
            # Configure git to use token
            git config --global credential.helper store
            echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
            
            # Update repository
            git fetch --all
            git reset --hard origin/main
            
            # Client build
            echo "Building client..."
            cd client 
            npm install
            npm run build
            
            # Server setup
            echo "Setting up server..."
            cd ../server 
            npm install
            
            # Return to project root
            cd ..
            
            # Restart PM2
            pm2 restart ecosystem.config.js